// One-time helper: downloads the Google Fonts used by the game into public/fonts
// and writes public/fonts/fonts.css (the local fallback loaded by src/services/fonts.js).
//
//   cd frontend && npm run fonts
//
// Needs internet once. Commit the resulting public/fonts folder so the event works offline.
// Requires Node 18+ (built-in fetch).

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400;500;600;700&family=Press+Start+2P&family=VT323&display=swap';

// A modern browser User-Agent makes Google serve woff2 files (smallest format)
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

// The UI is English-only; skip cyrillic/greek/vietnamese etc. to keep the download small
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const OUT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../public/fonts');

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const FORMAT_BY_EXT = { woff2: 'woff2', woff: 'woff', ttf: 'truetype' };

async function get(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res;
}

function parseFaces(css) {
  // Google's CSS looks like:  /* latin */ @font-face { font-family: ...; src: url(...) ...; unicode-range: ...; }
  const blockRe = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  const faces = [];
  let m;
  while ((m = blockRe.exec(css))) {
    const [, subset, body] = m;
    if (!KEEP_SUBSETS.has(subset)) continue;

    const prop = (name) => {
      const hit = new RegExp(`${name}\\s*:\\s*([^;]+);`).exec(body);
      return hit ? hit[1].trim() : undefined;
    };
    const urlHit = /url\(([^)]+)\)/.exec(body);
    const family = prop('font-family')?.replace(/['"]/g, '');
    if (!family || !urlHit) continue;

    faces.push({
      subset,
      family,
      style: prop('font-style') || 'normal',
      weight: prop('font-weight') || '400',
      range: prop('unicode-range'),
      url: urlHit[1].replace(/['"]/g, ''),
    });
  }
  return faces;
}

async function main() {
  console.log('Fetching Google Fonts CSS...');
  const css = await (await get(CSS_URL)).text();

  const faces = parseFaces(css);
  if (!faces.length) {
    throw new Error('No @font-face blocks found (did the Google CSS format change?)');
  }

  // Variable fonts return several weights pointing at the same file; download each file once
  const facesPerUrl = new Map();
  faces.forEach((f) => facesPerUrl.set(f.url, (facesPerUrl.get(f.url) || 0) + 1));

  const fileForUrl = new Map();
  for (const f of faces) {
    if (fileForUrl.has(f.url)) continue;
    const ext = (/\.(woff2|woff|ttf)(?:$|\?)/.exec(f.url) || [])[1] || 'woff2';
    const shared = facesPerUrl.get(f.url) > 1;
    const name = `${slug(f.family)}-${f.subset}-${shared ? 'variable' : f.weight}.${ext}`;
    fileForUrl.set(f.url, { name, ext });
  }

  await mkdir(OUT_DIR, { recursive: true });

  for (const [url, { name }] of fileForUrl) {
    process.stdout.write(`  downloading ${name} ... `);
    const buf = Buffer.from(await (await get(url)).arrayBuffer());
    await writeFile(path.join(OUT_DIR, name), buf);
    console.log(`${(buf.length / 1024).toFixed(1)} KB`);
  }

  const rules = faces.map((f) => {
    const { name, ext } = fileForUrl.get(f.url);
    const lines = [
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      '  font-display: swap;',
      `  src: url('./${name}') format('${FORMAT_BY_EXT[ext]}');`,
    ];
    if (f.range) lines.push(`  unicode-range: ${f.range};`);
    lines.push('}');
    return `/* ${f.family} ${f.weight} (${f.subset}) */\n${lines.join('\n')}`;
  });

  const header =
    '/* Generated by scripts/download-fonts.mjs. Local copy of the Google Fonts used by the game.\n' +
    '   Loaded by src/services/fonts.js only when Google Fonts cannot be reached. Do not edit by hand. */\n\n';
  await writeFile(path.join(OUT_DIR, 'fonts.css'), header + rules.join('\n\n') + '\n');

  console.log(`\nDone: ${fileForUrl.size} font files + fonts.css written to ${OUT_DIR}`);
  console.log('Commit public/fonts so the game works without internet.');
}

main().catch((err) => {
  console.error('\nFont download failed:', err.message);
  process.exit(1);
});
